### ISSUE TITLE
Rules doesn't detect non exhaustive when which are not direct child of named function

### ISSUE THREAD

**Issue by danikula** [olegosipenko/SamplesApp#3]
Rule checks only [direct children block expressions](https://github.com/olegosipenko/SamplesApp/blob/detekt/detekt-rules/src/main/java/com/github/olegosipenko/detektrules/NonExhaustiveWhen.kt#L28). So non exhaustive when below isn't detected:
```
sealed class S {
    object A: S()
    object B: S()
}
        
class WhenTester {
    fun checkS(state: S) {
        if (true) {
            when (state) {
              S.A -> println("a")
            }
        }
    }
}
```

**Comment by olegosipenko** [comment]
Thank you, I will look into question how to overcome this
